[workspace]
members = ["bindgen", "bridge", "cli", "ffi", "lib", "net", "rand", "scoped_task", "util", "vfs"]

[workspace.package]
version = "0.5.1"
authors = ["Adam Cigánek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
repository = "https://github.com/equalitie/ouisync"
license = "MPL-2.0"
edition = "2021"
rust-version = "1.65.0"

[workspace.dependencies]
async-trait = "0.1.64"
btdht = { git = "https://github.com/equalitie/btdht.git", rev = "5287b4a2bc507cde87903bc30ca2f1c548a31e18" }
bytes = "1.4.0"
camino = "1.0.9"
futures-util = { version = "0.3.21", default-features = false }
num_enum = { version = "0.5.11", default-features = false }
rmp-serde = "1.1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11.8"
thiserror = "1.0.31"
tokio = { version = "1.24.1", default-features = false }
tokio-stream = "0.1.9"
tokio-util = "0.7.4"
tracing = { version = "0.1.35" }
tracing-subscriber = { version = "0.3.15" }
turmoil = { git = "https://github.com/tokio-rs/turmoil" }

[profile.bench]
# Enable debug info so we can profile the benches
debug = 1

[patch.crates-io]
# Contains a fix to a race condition in `sqlx`'s `flume` dependency.
sqlx = { git = "https://github.com/inetic/sqlx.git", branch = "flume-race-fix" }
