[package]
name = "ouisync"
description = "Secure P2P file sharing"
version = "0.1.0"
authors = ["Adam Cigánek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
license = "MPL-2.0"
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"] # TODO: we might also need `staticlib` for ios

[dependencies]
anyhow = "1.0.40"
bincode = "1.3"
chacha20poly1305 = { version = "0.7.1" }
dirs = "3.0.1"
env_logger = "0.8.3"
futures = "0.3.14"
log = "0.4.14"
net2 = "0.2" # To be able to setsockopts before a socket is bound
rand = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.9.1"
slab = "0.4.3"
sqlx = { version = "0.5.2", features = ["runtime-tokio-rustls", "sqlite"] }
structopt = "0.3.21"
thiserror = "1.0.24"
tokio = { version = "1.5.0", features = ["fs", "macros", "rt-multi-thread", "signal", "sync", "time", "net"] }
zeroize = "1.2.0"
lru = "0.6.5"

[target.'cfg(unix)'.dependencies]
libc = "0.2.93"
fuser = "0.7.0"


[dev-dependencies]
proptest = "1.0"
tempfile = "3.2"
test-strategy = "0.1.1"