[workspace]
members = [
    "bridge",
    "cli",
    "ffi",
    "lib",
    "net",
    "rand",
    "scoped_task",
    "tracing_fmt",
    "utils/bindgen",
    "utils/btdht",
    "utils/stress-test",
    "vfs"
]
resolver = "2"

[workspace.package]
version = "0.5.2"
authors = ["Adam Cigánek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
repository = "https://github.com/equalitie/ouisync"
license = "MPL-2.0"
edition = "2021"
rust-version = "1.65.0"

[workspace.dependencies]
async-trait = "0.1.73"
btdht = { git = "https://github.com/equalitie/btdht.git", rev = "1d114b2" }
bytes = "1.5.0"
camino = "1.1.6"
clap = { version = "4.4.6", features = ["derive"] }
futures-util = { version = "0.3.28", default-features = false }
num_enum = { version = "0.7.0", default-features = false }
once_cell = "1.18.0"
rand = { package = "ouisync-rand", path = "rand" }
rcgen = { version = "0.11.3", default-features = false }
rmp-serde = "1.1.0"
rustls = { version = "0.21.0", default-features = false }
tokio-rustls = "0.24.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11.8"
thiserror = "1.0.49"
tokio = { version = "1.32.0", default-features = false }
tokio-stream = { version = "0.1.9", default-features = false }
tokio-util = "0.7.4"
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17" }
turmoil = { git = "https://github.com/tokio-rs/turmoil" }

[profile.bench]
# Enable debug info so we can profile the benches
debug = 1

[patch.crates-io]
# TODO: Remove this patch when sqlx 0.7.2 is released
sqlx = { git = "https://github.com/launchbadge/sqlx.git", rev = "e80291b2a771bf66e9c03f068fd196c7a47c1967" }
