[package]
name = "ouisync"
description = "Secure P2P file sharing"
version = "0.1.0"
authors = ["Adam Cigánek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
license = "MPL-2.0"
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"] # TODO: we might also need `staticlib` for ios

[dependencies]
async-std = "1.9.0"
futures-util = "0.3.14"
futures = "0.3.14"
anyhow = "1.0.40"
chacha20poly1305 = { version = "0.8.0-pre", features = ["alloc", "stream"] }
env_logger = "0.8.3"
log = "0.4.14"
rusqlite = { version = "0.25.0", features = ["bundled"] }
structopt = "0.3.21"
thiserror = "1.0.24"
tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread", "signal", "sync"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
net2 = "0.2" # To be able to setsockopts before a socket is bound
rand = "0.8.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2.93"
fuser = "0.7.0"

[patch.crates-io]
chacha20poly1305 = { git = "https://github.com/RustCrypto/AEADs.git" }
chacha20 = { git = "https://github.com/RustCrypto/stream-ciphers.git" }
