[workspace]
members = [
    "bindgen",
    "bridge",
    "cli",
    "ffi",
    "lib",
    "net",
    "rand",
    "scoped_task",
    "utils/btdht",
    "utils/stress-test",
    "vfs"
]

[workspace.package]
version = "0.5.1"
authors = ["Adam Cigánek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
repository = "https://github.com/equalitie/ouisync"
license = "MPL-2.0"
edition = "2021"
rust-version = "1.65.0"

[workspace.dependencies]
async-trait = "0.1.67"
btdht = { git = "https://github.com/equalitie/btdht.git", rev = "91f3f0da86130656643d1b787224b5777e18b459" }
bytes = "1.4.0"
camino = "1.0.9"
futures-util = { version = "0.3.27", default-features = false }
num_enum = { version = "0.5.11", default-features = false }
once_cell = "1.12.0"
rand = { package = "ouisync-rand", path = "rand" }
rmp-serde = "1.1.0"
rustls = { version = "0.20.8", default-features = false }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11.8"
thiserror = "1.0.31"
tokio = { version = "1.28.0", default-features = false }
tokio-stream = { version = "0.1.9", default-features = false }
tokio-util = "0.7.4"
tracing = { version = "0.1.35" }
tracing-subscriber = { version = "0.3.15" }
turmoil = { git = "https://github.com/tokio-rs/turmoil" }

[profile.bench]
# Enable debug info so we can profile the benches
debug = 1

[patch.crates-io]
# Contains a fix to a race condition in `sqlx`'s `flume` dependency.
sqlx = { git = "https://github.com/inetic/sqlx.git", branch = "flume-race-fix" }
