[workspace]

members = ["bindgen", "cli", "lib", "util"]

[patch.crates-io]
# TODO: remove these on next tokio-stream release (> 0.1.8)
tokio        = { git = "https://github.com/tokio-rs/tokio.git", rev = "83477c72" }
tokio-stream = { git = "https://github.com/tokio-rs/tokio.git", rev = "83477c72" }