[workspace]
members = ["bindgen", "cli", "ffi", "lib", "util", "vfs"]

[workspace.package]
version = "0.4.1"
authors = ["Adam Cigánek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
repository = "https://github.com/equalitie/ouisync"
license = "MPL-2.0"
edition = "2021"
rust-version = "1.65.0"

[workspace.dependencies]
tokio = { version = "1.21.0", default-features = false }
tracing = { version = "0.1.35" }
tracing-subscriber = { version = "0.3.15" }

[patch.crates-io]
sqlx = { git = "https://github.com/madadam/sqlx.git", rev = "6ca8667d" }

[profile.bench]
# Enable debug info so we can profile the benches
debug = 1
