[package]
name = "ouisync-cli"
description = "Secure P2P file sharing (command-line interface)"
version = "0.1.0"
authors = ["Adam Cigánek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
license = "MPL-2.0"
edition = "2021"
publish = false
default-run = "ouisync"

[[bin]]
name = "ouisync"
path = "src/main.rs"

[[test]]
name = "integration"
path = "tests/tests.rs"

[dependencies]
ouisync-lib = { package = "ouisync", version = "0.1", path = "../lib" }
anyhow = "1.0.40"
camino = "1.0.5"
dirs = "4.0.0"
env_logger = "0.9.0"
log = "0.4.14"
slab = "0.4.5"
structopt = "0.3.21"
tokio = { version = "1.14.0", features = ["signal"] }

[target.'cfg(any(target_os = "linux", target_os = "osx"))'.dependencies]
fuser = "0.9.0"
libc = "0.2.93"

[dev-dependencies]
proptest = "1.0"
rand = "0.8.4"
tempfile = "3.2"
test-strategy = "0.1.1"

