version: "3.9"

services:
  ouisync:
    image: equalitie/ouisync:latest
    container_name: ouisync
    ports:
      - "443:443/tcp"     # RPC
      - "444:444/tcp"     # Prometheus metrics
      - "20209:20209/tcp" # Sync protocol
      - "20209:20209/udp" # Sync protocol
    volumes:
      - "config:/config"
      - "store:/store"
      - "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/config/cert.pem"
      - "/etc/letsencrypt/live/${DOMAIN}/privkey.pem:/config/key.pem"

volumes:
  config:
  store:
