name: ffi_example
description: Example usage of the ouisync ffi bindings

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^2.4.2
  pedantic: ^1.11.0

ffigen:
    name: 'Bindings'
    description: 'Bindings to the ouisync library'
    output: 'gen/bindings.dart'
    headers:
        entry-points:
            - '../target/bindings.h'
        include-directives:
            - '**bindings.h'



