[package]
name = "ouisync-bridge"
description = "Secure P2P file sharing (backend - frontend bridge library)"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
camino = { workspace = true, features = ["serde1"] }
futures-util = { workspace = true }
num_enum = { workspace = true }
ouisync-lib = { package = "ouisync", path = "../lib" }
rmp-serde = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
ndk-sys = "0.3.0"
libc = "0.2.126"
log = "0.4.17"
once_cell = "1.9.0"
os_pipe = "0.9.2"
paranoid-android = "0.2.1"

[target.'cfg(not(target_os = "android"))'.dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
tempfile = "3.2"
