on: [push]

name: CI

jobs:
  build_and_test:
    name: OuiSync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: "Install dependencies"
        # NOTE: libfuse-dev is required only to build and run the ouisync
        # application. It is not required for building and using the ouisync
        # library.
        run: sudo apt-get install libfuse-dev

      - name: "Run clippy"
        run: cargo clippy

      - name: "Run tests"
        run: PROPTEST_CASES=32 cargo test
