on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: "Install dependencies"
        # NOTE: libfuse-dev is required only to build and run the ouisync
        # application. It is not required for building and using the ouisync
        # library.
        run: sudo apt-get install libfuse-dev

      - name: "Run clippy"
        run: cargo clippy

      - name: "Run tests"
        run: PROPTEST_CASES=32 cargo test
